FROM envoyproxy/envoy:latest
MAINTAINER Thanasis Tryfonos <thanasistryfonos@gmail.com>
RUN apt-get update \
 && apt-get -y install software-properties-common
RUN apt-get install -y curl
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer
COPY envoy-config/jservice-envoy.json /etc/envoy.json
COPY scripts/incontainer/start_jservice_in_docker.sh /home/start_jservice.sh
RUN chmod +x /home/start_jservice.sh
COPY services/jservice/target/jservice-0.0.1-SNAPSHOT.jar /home/jservice-0.0.1-SNAPSHOT.jar
EXPOSE 80
ENTRYPOINT ["/home/start_jservice.sh"]
