FROM envoyproxy/envoy:latest
MAINTAINER Thanasis Tryfonos <thanasistryfonos@gmail.com>
RUN apt-get -y update
RUN apt-get install -y curl
COPY envoy-config/goservice-envoy.json /etc/envoy.json
COPY scripts/incontainer/start_goservices_in_docker.sh /home/start_goservices.sh
COPY services/goservice/bin/goservice /home/serviceingo
RUN chmod +x /home/start_goservices.sh
EXPOSE 80
ENTRYPOINT ["/home/start_goservices.sh"]
